name: Send WHPJ to WeChat

on:
  workflow_dispatch:
  repository_dispatch:
    types: whpj-wechat

jobs:
  crawl:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute python script
      env:
        APPKEY: ${{ secrets.APPKEY }}
      run: |
        python main.py > exchange_rates.json
    - name: Upload json file
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: exchange_rates.json
